apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  {{- with .Values.mysql.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
      {{- if .Values.mysql.service.nodePort }}
      nodePort: {{ .Values.mysql.service.nodePort }}
      {{- end }}
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}