apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "city-population-service.fullname" . }}
  labels:
    {{- include "city-population-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "city-population-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "city-population-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ELASTICSEARCH_HOST
              value: {{ .Values.config.elasticsearch.host | quote }}
            - name: ELASTICSEARCH_PORT
              value: {{ .Values.config.elasticsearch.port | quote }}
            {{- if .Values.config.elasticsearch.user }}
            - name: ELASTICSEARCH_USER
              value: {{ .Values.config.elasticsearch.user | quote }}
            {{- end }}
            {{- if .Values.config.elasticsearch.password }}
            - name: ELASTICSEARCH_PASSWORD
              value: {{ .Values.config.elasticsearch.password | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}