apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "city-population-service.fullname" . }}
  labels:
    {{- include "city-population-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "city-population-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "city-population-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_HOST
              value: {{ .Values.config.mysql.host | quote }}
            - name: MYSQL_PORT
              value: {{ .Values.config.mysql.port | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.config.mysql.database | quote }}
            - name: MYSQL_USER
              value: {{ .Values.config.mysql.user | quote }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "city-population-service.fullname" . }}-mysql-secret
                  key: mysql-password
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}