apiVersion: v1
kind: Secret
metadata:
  name: {{ include "city-population-service.fullname" . }}-mysql-secret
  labels:
    {{- include "city-population-service.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-password: {{ .Values.mysql.auth.password | b64enc | quote }}