apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.fullname" . }}-config
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  my_custom.cnf: |-
{{ .Values.mysql.config.mycnf | indent 4 }}