# MySQL StatefulSet Configuration
mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  
  replicaCount: 1
  
  auth:
    rootPassword: rootpassword
    database: citydb
    username: cityapp
    password: password
    existingSecret: ""
  
  service:
    type: ClusterIP
    port: 3306
    nodePort: ""
    clusterIP: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    annotations: {}
  
  config:
    mycnf: |
      [mysqld]
      default_authentication_plugin=mysql_native_password
      skip-name-resolve
      explicit_defaults_for_timestamp
      max_allowed_packet=16M
      bind-address=0.0.0.0
      character-set-server=UTF8
      collation-server=utf8_general_ci
      
      [client]
      port=3306
      default-character-set=UTF8
  
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 256Mi
  
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
  
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
  
  podSecurityContext:
    fsGroup: 1001
  
  securityContext:
    runAsUser: 1001
  
  nodeSelector: {}
  affinity: {}
  tolerations: []