apiVersion: v2
name: city-population-service
description: A Helm chart for the City Population Service with MySQL database
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: mysql
    version: "9.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mysql.enabled