replicaCount: 1

image:
  repository: your-account-id.dkr.ecr.your-aws-region.amazonaws.com/city-population-service
  tag: mysql
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Application configuration
config:
  mysql:
    host: city-population-mysql
    port: 3306
    database: citydb
    user: cityapp

# MySQL configuration
mysql:
  enabled: true
  auth:
    database: citydb
    username: cityapp
    password: password123  # In production, use secrets management
    rootPassword: rootpassword123  # In production, use secrets management
  primary:
    persistence:
      enabled: true
      size: 8Gi