{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "city-population-service.fullname" . }}
  labels:
    {{- include "city-population-service.labels" . | nindent 4 }}
data:
  {{- if .Values.configMap.data }}
  {{- toYaml .Values.configMap.data | nindent 2 }}
  {{- end }}
  {{- if .Values.configMap.files }}
  {{- range $key, $value := .Values.configMap.files }}
  {{ $key }}: |-
{{ $value | indent 4 }}
  {{- end }}
  {{- end }}
{{- end }}