apiVersion: v1
kind: Secret
metadata:
  name: {{ include "city-population-service.fullname" . }}-secret
  labels:
    {{- include "city-population-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets }}
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}